# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=200)),
                ('cpf_cliente', models.IntegerField(default=0)),
                ('cnh_cliente', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_carro', models.IntegerField(choices=[(0, 'Moto'), (1, 'Carro'), (2, 'Utiliario'), (3, 'Caminhao')], default=1)),
            ],
        ),
    ]
