# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Veiculos',
        ),
    ]
