# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locacao', '0002_auto_20160119_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=200)),
                ('CPF_cliente', models.CharField(max_length=11)),
                ('CNH_cliente', models.CharField(max_length=20)),
                ('telefone_cliente', models.CharField(max_length=12)),
                ('email_cliente', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_carro', models.IntegerField()),
                ('placa', models.CharField(max_length=8)),
                ('modelo', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=20)),
                ('quilometragem', models.IntegerField()),
            ],
        ),
    ]
