# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0004_auto_20160120_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculos',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
