# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0005_veiculos_disponivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculos',
            name='tipo_carro',
            field=models.CharField(max_length=10),
        ),
    ]
