# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0006_auto_20160120_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucao',
            name='quilometragem_final',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='devolucao',
            name='quilometragem_inicial',
            field=models.IntegerField(default=0),
        ),
    ]
