# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0007_auto_20160120_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucao',
            name='data_devolucao',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='devolucao',
            name='data_locacao',
            field=models.CharField(max_length=10),
        ),
    ]
