# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaVeiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('tipo_cnh', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'categoria do veículo',
                'verbose_name_plural': 'categorias de veículos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='cpf')),
                ('tipo_cnh', models.CharField(max_length=2, verbose_name='tipo cnh')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='telefone')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_percorrido', models.FloatField(null=True, verbose_name='km percorrido')),
                ('data_entrega', models.DateTimeField(auto_now_add=True, verbose_name='data da entrega')),
            ],
            options={
                'verbose_name': 'devolução',
                'verbose_name_plural': 'devoluções',
            },
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateField(verbose_name='data locacão')),
                ('data_final', models.DateField(verbose_name='data de devolução')),
                ('km_inicial', models.FloatField(verbose_name='km inicial do veículo')),
                ('valor', models.FloatField(verbose_name='valor')),
                ('devolvido', models.BooleanField(default=False, verbose_name='devolvido')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'locação',
                'verbose_name_plural': 'locações',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50, verbose_name='modelo')),
                ('quilometragem', models.FloatField(verbose_name='quilometragem')),
                ('disponivel', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.CategoriaVeiculo', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'veículo',
                'verbose_name_plural': 'veículos',
            },
        ),
        migrations.AddField(
            model_name='locacao',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Veiculo', verbose_name='veiculo'),
        ),
        migrations.AddField(
            model_name='devolucao',
            name='locacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Locacao', unique=True, verbose_name='locação'),
        ),
    ]
