# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome da reserva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('finalizada', models.BooleanField(default=False, verbose_name='finalizada')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Cliente', verbose_name='cliente')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Veiculo', verbose_name='veículo')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
            },
        ),
    ]
