# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_reserva'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set([('veiculo', 'cliente')]),
        ),
    ]
