# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20160118_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cnh',
            field=models.CharField(max_length=20, verbose_name='tipo_cnh'),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set([]),
        ),
    ]
