# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20160118_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaveiculo',
            name='nome',
            field=models.CharField(max_length=50, unique=True, verbose_name='nome'),
        ),
    ]
