# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 03:33
from __future__ import unicode_literals

import car_location.location.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20160118_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[car_location.location.validators.validate_cpf], verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='telefone'),
        ),
    ]
